// Generated from quotes.csv — edit quotes.csv as the source of truth, then mirror here.
// (Kept as a JS file so it loads via <script> under file:// without fetch.)
window.MOTIVATIONAL_QUOTES=[
  {quote:"The expert in anything was once a beginner.",author:"Helen Hayes"},
  {quote:"Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.",author:"Richard Feynman"},
  {quote:"It always seems impossible until it's done.",author:"Nelson Mandela"},
  {quote:"The secret of getting ahead is getting started.",author:"Mark Twain"},
  {quote:"Wherever the art of medicine is loved, there is also a love of humanity.",author:"Hippocrates"},
  {quote:"You don't have to be great to start, but you have to start to be great.",author:"Zig Ziglar"},
  {quote:"Success is the sum of small efforts repeated day in and day out.",author:"Robert Collier"},
  {quote:"The future depends on what you do today.",author:"Mahatma Gandhi"},
  {quote:"Discipline is choosing between what you want now and what you want most.",author:"Abraham Lincoln"},
  {quote:"Don't watch the clock; do what it does. Keep going.",author:"Sam Levenson"},
  {quote:"A little progress each day adds up to big results.",author:"Anonymous"},
  {quote:"The only way to do great work is to love what you do.",author:"Steve Jobs"},
  {quote:"Strive for progress, not perfection.",author:"Anonymous"},
  {quote:"Hard work beats talent when talent doesn't work hard.",author:"Tim Notke"},
  {quote:"You are never too old to set another goal or to dream a new dream.",author:"C.S. Lewis"},
  {quote:"The harder the conflict, the greater the triumph.",author:"George Washington"},
  {quote:"Energy and persistence conquer all things.",author:"Benjamin Franklin"},
  {quote:"What we know is a drop, what we don't know is an ocean.",author:"Isaac Newton"},
  {quote:"Every accomplishment starts with the decision to try.",author:"John F. Kennedy"},
  {quote:"You don't have to see the whole staircase, just take the first step.",author:"Martin Luther King Jr."},
  {quote:"Wherever you go, no matter what the weather, always bring your own sunshine.",author:"Anthony J. D'Angelo"},
  {quote:"The good physician treats the disease; the great physician treats the patient who has the disease.",author:"William Osler"},
  {quote:"Knowledge is of no value unless you put it into practice.",author:"Anton Chekhov"},
  {quote:"Patience and perseverance have a magical effect before which difficulties disappear.",author:"John Quincy Adams"},
  {quote:"It does not matter how slowly you go, so long as you do not stop.",author:"Confucius"},
  {quote:"Listen to the patient, he is telling you the diagnosis.",author:"William Osler"},
  {quote:"There is no substitute for hard work.",author:"Thomas Edison"},
  {quote:"Quality is not an act, it is a habit.",author:"Aristotle"},
  {quote:"The man who moves a mountain begins by carrying away small stones.",author:"Confucius"},
  {quote:"Believe you can and you're halfway there.",author:"Theodore Roosevelt"},
  {quote:"Medicine is a science of uncertainty and an art of probability.",author:"William Osler"},
  {quote:"Fall seven times, stand up eight.",author:"Japanese Proverb"},
  {quote:"The cure for boredom is curiosity. There is no cure for curiosity.",author:"Dorothy Parker"},
  {quote:"Don't count the days, make the days count.",author:"Muhammad Ali"},
  {quote:"Be regular and orderly in your life, that you may be violent and original in your work.",author:"Gustave Flaubert"},
  {quote:"Small daily improvements over time lead to stunning results.",author:"Robin Sharma"},
  {quote:"The only impossible journey is the one you never begin.",author:"Tony Robbins"},
  {quote:"Care more for the individual patient than for the special features of the disease.",author:"William Osler"},
  {quote:"You cannot escape the responsibility of tomorrow by evading it today.",author:"Abraham Lincoln"},
  {quote:"Wisdom is the daughter of experience.",author:"Leonardo da Vinci"},
  {quote:"He who has a why to live for can bear almost any how.",author:"Friedrich Nietzsche"},
  {quote:"Action is the foundational key to all success.",author:"Pablo Picasso"},
  {quote:"Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.",author:"Alexander Graham Bell"},
  {quote:"Don't let what you cannot do interfere with what you can do.",author:"John Wooden"},
  {quote:"The roots of education are bitter, but the fruit is sweet.",author:"Aristotle"},
  {quote:"Success is not final, failure is not fatal: it is the courage to continue that counts.",author:"Winston Churchill"},
  {quote:"The best preparation for tomorrow is doing your best today.",author:"H. Jackson Brown Jr."},
  {quote:"In medicine, the art of saying nothing is as important as the science of saying something.",author:"Anonymous"},
  {quote:"Push yourself, because no one else is going to do it for you.",author:"Anonymous"},
  {quote:"Great things never come from comfort zones.",author:"Anonymous"},
];
